In [1]:
import numpy as np

# Step Function
def step(x):
    return np.where(x >= 0, 1, -1)

# Step 1: Define Patterns (4 vectors)
patterns = np.array([
    [1, 1, -1, -1],
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [-1, -1, 1, 1]
])

# Step 2: Initialize Weight Matrix
n = patterns.shape[1]
W = np.zeros((n, n))

# Hebbian Learning Rule
for p in patterns:
    W += np.outer(p, p)

# Remove self-connections
np.fill_diagonal(W, 0)

print("Weight Matrix:\n", W)

# Step 3: Recall Function
def hopfield_recall(input_pattern, W, steps=5):
    x = input_pattern.copy()
    for _ in range(steps):
        x = step(np.dot(W, x))
    return x

# Step 4: Test with Noisy Input
test_input = np.array([1, 1, -1, 1])  # noisy version

output = hopfield_recall(test_input, W)

print("\nInput Pattern:", test_input)
print("Recovered Pattern:", output)

Weight Matrix:
 [[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]

Input Pattern: [ 1  1 -1  1]
Recovered Pattern: [-1  1 -1 -1]
